name: CI Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: npm ci

      # test code
      - name: Run tests
        run: npm test

      # generate and lint types
      - name: Generate types
        run: npm start
      - name: Lint types
        run: npm run lint
        env:
          GAPI_MAX_PARALLEL: 3

      # upload failed type for investigation
      - name: Copy discovery service response
        if: failure()
        run: cp .tmp/${{ env.FAILED_TYPE }}.json types/${{ env.FAILED_TYPE }}
      - name: Upload failed type
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ${{ env.FAILED_TYPE }}
          path: types/${{ env.FAILED_TYPE }}
